// Package sub is generated by whit yammm go generator. DO NOT EDIT.
package sub
//nolint
type Car struct {
    RegisteredVehicle
}
type Person struct {
    Entity
    Birthday string `json:"birthday" yaml:"birthday"`
    Name string `json:"name" yaml:"name"`
    Retired *Retired `json:"Retired,omitempty" yaml:"Retired,omitempty"`
}
type Retirement struct {
    Id string `json:"id" yaml:"id"`
}
type Retired struct {
    HAS_RETIRED_Retirement *EDGE_HAS_RETIRED_Retirement `json:"HAS_RETIRED_Retirement,omitempty" yaml:"HAS_RETIRED_Retirement,omitempty"`
}
type MC struct {
    RegisteredVehicle
}
type Registered struct {
    RegNbr string `json:"regNbr" yaml:"regNbr"`
    RegistrationDate string `json:"registrationDate" yaml:"registrationDate"`
    DeregisterationDate string `json:"deregisterationDate,omitempty" yaml:"deregisterationDate,omitempty"`
    REGISTERED_WITH_Registrar *EDGE_REGISTERED_WITH_Registrar `json:"REGISTERED_WITH_Registrar,omitempty" yaml:"REGISTERED_WITH_Registrar,omitempty"`
}
type Registrar struct {
    Name string `json:"name" yaml:"name"`
}
type Vehicle struct {
    Color string `json:"color,omitempty" yaml:"color,omitempty"`
    Model string `json:"model,omitempty" yaml:"model,omitempty"`
}
type RegisteredVehicle struct {
    Vehicle
    Registered
}
type Bicycle struct {
    Vehicle
    BikeID string `json:"bikeID" yaml:"bikeID"`
}
type MotorVehicleOwner struct {
    OWNS_VEHICLE_RegisteredVehicle *EDGE_OWNS_VEHICLE_RegisteredVehicle `json:"OWNS_VEHICLE_RegisteredVehicle,omitempty" yaml:"OWNS_VEHICLE_RegisteredVehicle,omitempty"`
}
type Entity struct {
    MotorVehicleOwner *MotorVehicleOwner `json:"MotorVehicleOwner,omitempty" yaml:"MotorVehicleOwner,omitempty"`
}
type Company struct {
    Entity
}
type Graph struct {
    Cars []*Car `json:"Cars,omitempty" yaml:"Cars,omitempty"`
    People []*Person `json:"People,omitempty" yaml:"People,omitempty"`
    Retirements []*Retirement `json:"Retirements,omitempty" yaml:"Retirements,omitempty"`
    Retireds []*Retired `json:"Retireds,omitempty" yaml:"Retireds,omitempty"`
    MCS []*MC `json:"MCS,omitempty" yaml:"MCS,omitempty"`
    Registrars []*Registrar `json:"Registrars,omitempty" yaml:"Registrars,omitempty"`
    Bicycles []*Bicycle `json:"Bicycles,omitempty" yaml:"Bicycles,omitempty"`
    Companies []*Company `json:"Companies,omitempty" yaml:"Companies,omitempty"`
}
// data type: timeStamp string
type EDGE_HAS_RETIRED_Retirement struct {
    FromDate string `json:"fromDate" yaml:"fromDate"`
    Where struct {
        Id string `json:"id" yaml:"id"`
    } `json:"Where" yaml:"Where"`
}
type EDGE_REGISTERED_WITH_Registrar struct {
    Where struct {
        Name string `json:"name" yaml:"name"`
    } `json:"Where" yaml:"Where"`
}
type EDGE_OWNS_VEHICLE_RegisteredVehicle struct {
    FromDate string `json:"fromDate" yaml:"fromDate"`
    ToDate string `json:"toDate,omitempty" yaml:"toDate,omitempty"`
    Where struct {
        RegNbr string `json:"regNbr" yaml:"regNbr"`
    } `json:"Where" yaml:"Where"`
}
const SerializedModel =`
{
	"name": "main",
	"types": [
		{
			"name": "Car",
			"plural_name": "Cars",
			"inherits": [
				"RegisteredVehicle"
			]
		},
		{
			"name": "Person",
			"plural_name": "People",
			"properties": [
				{
					"name": "birthday",
					"type": "#timeStamp"
				},
				{
					"name": "name",
					"type": "string",
					"primary": true
				}
			],
			"inherits": [
				"Entity"
			],
			"mixins": [
				"Retired"
			]
		},
		{
			"name": "Retirement",
			"plural_name": "Retirements",
			"properties": [
				{
					"name": "id",
					"type": "string",
					"primary": true
				}
			]
		},
		{
			"name": "Retired",
			"plural_name": "Retireds",
			"associations": [
				{
					"to": "Retirement",
					"optional": true,
					"many": false,
					"name": "HAS_RETIRED",
					"properties": [
						{
							"name": "fromDate",
							"type": "#timeStamp"
						}
					]
				}
			]
		},
		{
			"name": "MC",
			"plural_name": "MCS",
			"inherits": [
				"RegisteredVehicle"
			]
		},
		{
			"name": "Registered",
			"plural_name": "Registereds",
			"properties": [
				{
					"name": "regNbr",
					"type": "string",
					"primary": true
				},
				{
					"name": "registrationDate",
					"type": "#timeStamp"
				},
				{
					"name": "deregisterationDate",
					"type": "#timeStamp",
					"optional": true
				}
			],
			"associations": [
				{
					"to": "Registrar",
					"optional": true,
					"many": false,
					"name": "REGISTERED_WITH"
				}
			],
			"is_abstract": true
		},
		{
			"name": "Registrar",
			"plural_name": "Registrars",
			"properties": [
				{
					"name": "name",
					"type": "\"DMV\"|\"ABC\"",
					"primary": true
				}
			]
		},
		{
			"name": "Vehicle",
			"plural_name": "Vehicles",
			"properties": [
				{
					"name": "color",
					"type": "string",
					"optional": true
				},
				{
					"name": "model",
					"type": "string",
					"optional": true
				}
			],
			"is_abstract": true
		},
		{
			"name": "RegisteredVehicle",
			"plural_name": "RegisteredVehicles",
			"inherits": [
				"Vehicle",
				"Registered"
			],
			"is_abstract": true
		},
		{
			"name": "Bicycle",
			"plural_name": "Bicycles",
			"properties": [
				{
					"name": "bikeID",
					"type": "string",
					"primary": true
				}
			],
			"inherits": [
				"Vehicle"
			]
		},
		{
			"name": "MotorVehicleOwner",
			"plural_name": "MotorVehicleOwners",
			"associations": [
				{
					"to": "RegisteredVehicle",
					"optional": true,
					"many": false,
					"name": "OWNS_VEHICLE",
					"properties": [
						{
							"name": "fromDate",
							"type": "#timeStamp"
						},
						{
							"name": "toDate",
							"type": "#timeStamp",
							"optional": true
						}
					]
				}
			],
			"is_mixin": true
		},
		{
			"name": "Entity",
			"plural_name": "Entities",
			"mixins": [
				"MotorVehicleOwner"
			],
			"is_abstract": true
		},
		{
			"name": "Company",
			"plural_name": "Companies",
			"inherits": [
				"Entity"
			]
		}
	],
	"data_types": [
		{
			"name": "timeStamp",
			"type": "string"
		}
	]
}
`
