// Package cars is generated by whit yammm go generator. DO NOT EDIT.
package cars
//nolint
type Car struct {
    RegisteredVehicle
}
type Person struct {
    Entity
    Retired
    Birthday *string `json:"birthday,omitempty" yaml:"birthday,omitempty"`
}
type Retirement struct {
    Id string `json:"id" yaml:"id"`
    Rid string `json:"rid" yaml:"rid"`
}
type Retired struct {
    Id string `json:"id" yaml:"id"`
    HAS_RETIRED_Retirement *EDGE_HAS_RETIRED_Retirement `json:"HAS_RETIRED_Retirement,omitempty" yaml:"HAS_RETIRED_Retirement,omitempty"`
}
type MC struct {
    RegisteredVehicle
}
type Registered struct {
    Id string `json:"id" yaml:"id"`
    RegNbr string `json:"regNbr" yaml:"regNbr"`
    RegistrationDate string `json:"registrationDate" yaml:"registrationDate"`
    DeregistrationDate *string `json:"deregistrationDate,omitempty" yaml:"deregistrationDate,omitempty"`
    REGISTERED_WITH_Registrar *EDGE_REGISTERED_WITH_Registrar `json:"REGISTERED_WITH_Registrar,omitempty" yaml:"REGISTERED_WITH_Registrar,omitempty"`
}
type Registrar struct {
    Id string `json:"id" yaml:"id"`
    Name string `json:"name" yaml:"name"`
}
type Vehicle struct {
    Id string `json:"id" yaml:"id"`
    Color *string `json:"color,omitempty" yaml:"color,omitempty"`
    Model *string `json:"model,omitempty" yaml:"model,omitempty"`
}
type RegisteredVehicle struct {
    Vehicle
    Registered
}
type Bicycle struct {
    Vehicle
    BikeID string `json:"bikeID" yaml:"bikeID"`
}
type MotorVehicleOwner struct {
    Id string `json:"id" yaml:"id"`
    OWNS_VEHICLE_Vehicles []*EDGE_OWNS_VEHICLE_Vehicle `json:"OWNS_VEHICLE_Vehicles,omitempty" yaml:"OWNS_VEHICLE_Vehicles,omitempty"`
}
type Entity struct {
    MotorVehicleOwner
    Name string `json:"name" yaml:"name"`
}
type Company struct {
    Entity
}
type Graph struct {
    Cars []*Car `json:"Cars,omitempty" yaml:"Cars,omitempty"`
    People []*Person `json:"People,omitempty" yaml:"People,omitempty"`
    Retirements []*Retirement `json:"Retirements,omitempty" yaml:"Retirements,omitempty"`
    Retireds []*Retired `json:"Retireds,omitempty" yaml:"Retireds,omitempty"`
    MCS []*MC `json:"MCS,omitempty" yaml:"MCS,omitempty"`
    Registrars []*Registrar `json:"Registrars,omitempty" yaml:"Registrars,omitempty"`
    Bicycles []*Bicycle `json:"Bicycles,omitempty" yaml:"Bicycles,omitempty"`
    MotorVehicleOwners []*MotorVehicleOwner `json:"MotorVehicleOwners,omitempty" yaml:"MotorVehicleOwners,omitempty"`
    Companies []*Company `json:"Companies,omitempty" yaml:"Companies,omitempty"`
}
type EDGE_HAS_RETIRED_Retirement struct {
    FromDate string `json:"fromDate" yaml:"fromDate"`
    Where struct {
        Id string `json:"id" yaml:"id"`
        Rid string `json:"rid" yaml:"rid"`
    } `json:"Where" yaml:"Where"`
}
type EDGE_REGISTERED_WITH_Registrar struct {
    Where struct {
        Id string `json:"id" yaml:"id"`
        Name string `json:"name" yaml:"name"`
    } `json:"Where" yaml:"Where"`
}
type EDGE_OWNS_VEHICLE_Vehicle struct {
    FromDate string `json:"fromDate" yaml:"fromDate"`
    ToDate *string `json:"toDate,omitempty" yaml:"toDate,omitempty"`
    Where struct {
        Id string `json:"id" yaml:"id"`
    } `json:"Where" yaml:"Where"`
}
const SerializedModel =`
{
	"line": 1,
	"column": 7,
	"source": "debugdata/cars_in_yammm.yammm",
	"name": "cars",
	"types": [
		{
			"line": 3,
			"column": 5,
			"source": "debugdata/cars_in_yammm.yammm",
			"name": "Car",
			"plural_name": "Cars",
			"properties": [
				{
					"line": 1,
					"column": 1,
					"source": "\u003cyammm built in 'id UUID primary'\u003e",
					"name": "id",
					"datatype": [
						"UUID"
					],
					"primary": true
				}
			],
			"inherits": [
				"RegisteredVehicle"
			]
		},
		{
			"line": 5,
			"column": 5,
			"source": "debugdata/cars_in_yammm.yammm",
			"name": "Person",
			"plural_name": "People",
			"properties": [
				{
					"line": 1,
					"column": 1,
					"source": "\u003cyammm built in 'id UUID primary'\u003e",
					"name": "id",
					"datatype": [
						"UUID"
					],
					"primary": true
				},
				{
					"line": 6,
					"column": 4,
					"source": "debugdata/cars_in_yammm.yammm",
					"name": "birthday",
					"datatype": [
						"Date"
					],
					"optional": true
				}
			],
			"inherits": [
				"Entity",
				"Retired"
			]
		},
		{
			"line": 8,
			"column": 5,
			"source": "debugdata/cars_in_yammm.yammm",
			"name": "Retirement",
			"plural_name": "Retirements",
			"properties": [
				{
					"line": 1,
					"column": 1,
					"source": "\u003cyammm built in 'id UUID primary'\u003e",
					"name": "id",
					"datatype": [
						"UUID"
					],
					"primary": true
				},
				{
					"line": 9,
					"column": 4,
					"source": "debugdata/cars_in_yammm.yammm",
					"name": "rid",
					"datatype": [
						"String",
						"",
						""
					],
					"primary": true
				}
			]
		},
		{
			"line": 11,
			"column": 5,
			"source": "debugdata/cars_in_yammm.yammm",
			"name": "Retired",
			"plural_name": "Retireds",
			"properties": [
				{
					"line": 1,
					"column": 1,
					"source": "\u003cyammm built in 'id UUID primary'\u003e",
					"name": "id",
					"datatype": [
						"UUID"
					],
					"primary": true
				}
			],
			"associations": [
				{
					"name": "HAS_RETIRED",
					"to": "Retirement",
					"optional": true,
					"many": false,
					"properties": [
						{
							"name": "fromDate",
							"datatype": [
								"Date"
							]
						}
					]
				}
			]
		},
		{
			"line": 16,
			"column": 5,
			"source": "debugdata/cars_in_yammm.yammm",
			"name": "MC",
			"plural_name": "MCS",
			"properties": [
				{
					"line": 1,
					"column": 1,
					"source": "\u003cyammm built in 'id UUID primary'\u003e",
					"name": "id",
					"datatype": [
						"UUID"
					],
					"primary": true
				}
			],
			"inherits": [
				"RegisteredVehicle"
			]
		},
		{
			"line": 19,
			"column": 14,
			"source": "debugdata/cars_in_yammm.yammm",
			"name": "Registered",
			"plural_name": "Registereds",
			"properties": [
				{
					"line": 1,
					"column": 1,
					"source": "\u003cyammm built in 'id UUID primary'\u003e",
					"name": "id",
					"datatype": [
						"UUID"
					],
					"primary": true
				},
				{
					"line": 20,
					"column": 4,
					"source": "debugdata/cars_in_yammm.yammm",
					"name": "regNbr",
					"datatype": [
						"String",
						"",
						""
					],
					"primary": true
				},
				{
					"line": 21,
					"column": 4,
					"source": "debugdata/cars_in_yammm.yammm",
					"name": "registrationDate",
					"datatype": [
						"Date"
					]
				},
				{
					"line": 22,
					"column": 4,
					"source": "debugdata/cars_in_yammm.yammm",
					"name": "deregistrationDate",
					"datatype": [
						"Date"
					],
					"optional": true
				}
			],
			"associations": [
				{
					"name": "REGISTERED_WITH",
					"to": "Registrar",
					"optional": true,
					"many": false
				}
			],
			"is_abstract": true
		},
		{
			"line": 25,
			"column": 5,
			"source": "debugdata/cars_in_yammm.yammm",
			"name": "Registrar",
			"plural_name": "Registrars",
			"properties": [
				{
					"line": 1,
					"column": 1,
					"source": "\u003cyammm built in 'id UUID primary'\u003e",
					"name": "id",
					"datatype": [
						"UUID"
					],
					"primary": true
				},
				{
					"line": 26,
					"column": 4,
					"source": "debugdata/cars_in_yammm.yammm",
					"name": "name",
					"datatype": [
						"Enum",
						"DMV",
						"ABC"
					],
					"primary": true
				}
			]
		},
		{
			"line": 28,
			"column": 14,
			"source": "debugdata/cars_in_yammm.yammm",
			"name": "Vehicle",
			"plural_name": "Vehicles",
			"properties": [
				{
					"line": 1,
					"column": 1,
					"source": "\u003cyammm built in 'id UUID primary'\u003e",
					"name": "id",
					"datatype": [
						"UUID"
					],
					"primary": true
				},
				{
					"line": 29,
					"column": 4,
					"source": "debugdata/cars_in_yammm.yammm",
					"name": "color",
					"datatype": [
						"String",
						"",
						""
					],
					"optional": true
				},
				{
					"line": 30,
					"column": 4,
					"source": "debugdata/cars_in_yammm.yammm",
					"name": "model",
					"datatype": [
						"String",
						"",
						""
					],
					"optional": true
				}
			],
			"is_abstract": true
		},
		{
			"line": 33,
			"column": 14,
			"source": "debugdata/cars_in_yammm.yammm",
			"name": "RegisteredVehicle",
			"plural_name": "RegisteredVehicles",
			"properties": [
				{
					"line": 1,
					"column": 1,
					"source": "\u003cyammm built in 'id UUID primary'\u003e",
					"name": "id",
					"datatype": [
						"UUID"
					],
					"primary": true
				}
			],
			"inherits": [
				"Vehicle",
				"Registered"
			],
			"is_abstract": true
		},
		{
			"line": 36,
			"column": 5,
			"source": "debugdata/cars_in_yammm.yammm",
			"name": "Bicycle",
			"plural_name": "Bicycles",
			"properties": [
				{
					"line": 1,
					"column": 1,
					"source": "\u003cyammm built in 'id UUID primary'\u003e",
					"name": "id",
					"datatype": [
						"UUID"
					],
					"primary": true
				},
				{
					"line": 37,
					"column": 4,
					"source": "debugdata/cars_in_yammm.yammm",
					"name": "bikeID",
					"datatype": [
						"String",
						"",
						""
					],
					"primary": true
				}
			],
			"inherits": [
				"Vehicle"
			]
		},
		{
			"line": 39,
			"column": 5,
			"source": "debugdata/cars_in_yammm.yammm",
			"name": "MotorVehicleOwner",
			"plural_name": "MotorVehicleOwners",
			"properties": [
				{
					"line": 1,
					"column": 1,
					"source": "\u003cyammm built in 'id UUID primary'\u003e",
					"name": "id",
					"datatype": [
						"UUID"
					],
					"primary": true
				}
			],
			"associations": [
				{
					"name": "OWNS_VEHICLE",
					"to": "Vehicle",
					"optional": true,
					"many": true,
					"properties": [
						{
							"name": "fromDate",
							"datatype": [
								"Date"
							]
						},
						{
							"name": "toDate",
							"datatype": [
								"Date"
							],
							"optional": true
						}
					]
				}
			]
		},
		{
			"line": 45,
			"column": 14,
			"source": "debugdata/cars_in_yammm.yammm",
			"name": "Entity",
			"plural_name": "Entities",
			"properties": [
				{
					"line": 1,
					"column": 1,
					"source": "\u003cyammm built in 'id UUID primary'\u003e",
					"name": "id",
					"datatype": [
						"UUID"
					],
					"primary": true
				},
				{
					"line": 46,
					"column": 8,
					"source": "debugdata/cars_in_yammm.yammm",
					"name": "name",
					"datatype": [
						"String",
						"",
						""
					],
					"primary": true
				}
			],
			"inherits": [
				"MotorVehicleOwner"
			],
			"is_abstract": true
		},
		{
			"line": 48,
			"column": 5,
			"source": "debugdata/cars_in_yammm.yammm",
			"name": "Company",
			"plural_name": "Companies",
			"properties": [
				{
					"line": 1,
					"column": 1,
					"source": "\u003cyammm built in 'id UUID primary'\u003e",
					"name": "id",
					"datatype": [
						"UUID"
					],
					"primary": true
				}
			],
			"inherits": [
				"Entity"
			]
		}
	]
}
`
