name: Release Whit (GoReleaser)

on:
  push:
    tags: ["v*"]         


permissions:
  contents: write        


jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos:   [linux]              
        goarch: [amd64]            

    steps:
      - name: Checkout Whit source
        uses: actions/checkout@v4


      - name: Set up Go 1.21
        uses: actions/setup-go@v3
        with:
          go-version: 1.21           
        id: go

      - name: Import GPG key
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          version: '~> v2'
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          GPG_FINGERPRINT: ${{ steps.import_gpg.outputs.fingerprint }}