name: Build & Release Whit (Go)

on:
  push:
    tags: ["v*"]         

permissions:
  contents: write        

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos:   [linux]              
        goarch: [amd64]            

    steps:
      - name: Checkout Whit source
        uses: actions/checkout@v4

      - name: Set up Go 1.21
        uses: actions/setup-go@v3
        with:
          go-version: 1.21           
        id: go

      - name: Build Whit ${{ matrix.goos }}/${{ matrix.goarch }}
        env:
          GOOS:   ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
          CGO_ENABLED: 0            
        run: |
          go build -ldflags="-s -w" -o whit .
          BIN="whit-${{ github.ref_name }}-${GOOS}-${GOARCH}"
          mv whit "$BIN"
          tar -czf "$BIN.tar.gz" "$BIN"
          echo "ASSET=$BIN.tar.gz" >> "$GITHUB_ENV"

      - name: Upload binary to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ env.ASSET }}
          generate_release_notes: true